### ISSUE TITLE
Timeouts / Segfaults or Endless run on Kubernetes pods

### ISSUE THREAD

**Issue by Leyart** [opengrep/opengrep#204]
**Describe the bug**
We are trying to run opengrep with the following cli setting in a kubernetes pod of our build agents running as a pipeline step in buildkite:

```shell
opengrep scan --error --metrics=off --sarif-output=ogrep.sarif --config "rulesdir/community" --jobs=4 --max-memory=2000 --timeout=3 --timeout-threshold=3 path/to/repository
```

The repository to be scanned is a monorepo.

The rules are downloaded via semgrep-rules-manager in a cached folder

Depending on the run, 3 different things might be happening:

- Cancelled by asyncio

```shell
Traceback (most recent call last):
  File "asyncio/subprocess.py", line 135, in wait
  File "asyncio/base_subprocess.py", line 235, in _wait
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "asyncio/tasks.py", line 490, in wait_for
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "semgrep/commands/wrapper.py", line 37, in wrapper
  File "semgrep/commands/scan.py", line 811, in scan
  File "semgrep/tracing.py", line 263, in inner
  File "semgrep/run_scan.py", line 789, in run_scan
  File "semgrep/tracing.py", line 263, in inner
  File "semgrep/run_scan.py", line 338, in run_rules
  File "semgrep/core_runner.py", line 1169, in invoke_semgrep_core
  File "semgrep/core_runner.py", line 1142, in _run_rules_direct_to_semgrep_core
  File "semgrep/core_runner.py", line 1107, in _run_rules_direct_to_semgrep_core
  File "semgrep/core_runner.py", line 1025, in _run_rules_direct_to_semgrep_core_helper
  File "semgrep/tracing.py", line 263, in inner
  File "semgrep/core_runner.py", line 497, in execute
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 647, in run_until_complete
  File "semgrep/core_runner.py", line 450, in _stream_exec_subprocess
  File "asyncio/tasks.py", line 492, in wait_for
asyncio.exceptions.TimeoutError
``` 

- Crashing with a segfault
/path/to/my/calling/script.sh: line 104: 2299804 Segmentation fault      (core dumped) 

- Endless run for hours (up to 2 days, at that point our agents get killed by our infrastructure due to running for too long)

With the exact same CLI parameters, codebase analyzed and tool version running on a Apple M3 Pro, the scan is completed within around 30 minutes

**To Reproduce**
Unfortunately very hard to do so since the repository is private. 
The kubernetes pods don't have limits or requests on resources. 
I assume we are not the only ones trying to run semgrep / opengrep in K8s but I was not able to find other similar reports.
--debug or --verbose options are not helping to identify the root cause of the issue
The repository looks like this when running a scan:

<img width="442" alt="Image" src="https://github.com/user-attachments/assets/468dc620-3cbf-413e-8698-206d29e8f8ed" />

We already followed the suggestions in https://semgrep.dev/docs/kb/semgrep-code/semgrep-scan-troubleshooting#memory-usage-issues-oom-errors

Running with --jobs=1 seems to reduce the crash occurrences, but guarantees that we end up in an "endless" scan

**Expected behavior**
I would expect the tool to run in a reasonable time (at most a couple of hours), similarly to what happens on my local machine (definitely not 17/18 hours)

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Opengrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Opengrep 1.0.2
Python 3.11.2
ulimit unlimited
cat /sys/fs/cgroup/cpuset.cpus.effective 0-15
free
               total        used        free      shared  buff/cache   available
Mem:        65843208    45054644     8008620       29752    13561676    20788564
Swap:              0           0           0

**Use case**
Solving this issue will enable us to run daily or weekly jobs on our entire codebase to get a full report and track the improvements and quality of our source code

Thanks a lot for the support, and let me know if there is anything I can provide additionally in terms of logs or different cli parameters that I could try to improve the situation

**Comment by dimitris-m** [comment]
Hi, thanks for this report.

We have discovered an issue that is related to "endless" runs and are working on a solution.

We'll keep you posted here.

**Comment by dimitris-m** [comment]
Would you try out this new version? 

https://github.com/opengrep/opengrep/releases/tag/v1.1.4 

Some additional suggestions: 
- consider passing `--quiet` to suppress all logs, this will make it run a little faster; unless if you need the default logs and outputs.
- if possible, allow for more memory, perhaps 4GB.

**Comment by Leyart** [comment]
I will test it in the next days.
By limiting filesize, rulesets and setting jobs=1 I was able to have a more or less stable setup, even though from time to time logs were not printed and the tool is getting into the nefarious endless loop.
I really hope that by switching to normal mutexes the problem will be solved.
Thanks again for the quick intervention

**Comment by dimitris-m** [comment]
> I will test it in the next days. By limiting filesize, rulesets and setting jobs=1 I was able to have a more or less stable setup, even though from time to time logs were not printed and the tool is getting into the nefarious endless loop. I really hope that by switching to normal mutexes the problem will be solved. Thanks again for the quick intervention

It should be fixed, because in fact it was not an endless loop but rather a deadlock, which we reproduced: in some cases the logs mutex was acquired but never released, blocking subsequent calls to logging functions.

**Comment by Leyart** [comment]
@dimitris-m Thanks so much for the new version. 
I can confirm that now we can use a broader set of rules and the tool completes the scan successfully, which was necessary for us to fully adopt the product :)

Unfortunately, this works just with the --jobs=1 flag.
If I try to use multiple jobs or leaving the default (--jobs=4), the run still crashes with 

```shell
Traceback (most recent call last):
  File "asyncio/subprocess.py", line 135, in wait
  File "asyncio/base_subprocess.py", line 235, in _wait
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "asyncio/tasks.py", line 490, in wait_for
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "semgrep/commands/wrapper.py", line 37, in wrapper
  File "semgrep/commands/scan.py", line 811, in scan
  File "semgrep/tracing.py", line 263, in inner
  File "semgrep/run_scan.py", line 800, in run_scan
  File "semgrep/tracing.py", line 263, in inner
  File "semgrep/run_scan.py", line 349, in run_rules
  File "semgrep/core_runner.py", line 1168, in invoke_semgrep_core
  File "semgrep/core_runner.py", line 1141, in _run_rules_direct_to_semgrep_core
  File "semgrep/core_runner.py", line 1106, in _run_rules_direct_to_semgrep_core
  File "semgrep/core_runner.py", line 1024, in _run_rules_direct_to_semgrep_core_helper
  File "semgrep/tracing.py", line 263, in inner
  File "semgrep/core_runner.py", line 496, in execute
  File "asyncio/runners.py", line 44, in run
  File "asyncio/base_events.py", line 647, in run_until_complete
  File "semgrep/core_runner.py", line 449, in _stream_exec_subprocess
  File "asyncio/tasks.py", line 492, in wait_for
asyncio.exceptions.TimeoutError
```

This is happening with the opengrep_manylinux_x86 version. 
Is there anything that comes to mind to why this could still be a problem?

**Comment by dimitris-m** [comment]
@Leyart are you able to do a run with `--verbose` and share some logs. Redacted as needed, or just any fragment you find relevant... We are interested at what happens near the end of the run, for example does the OCaml binary crash?

**Comment by dimitris-m** [comment]
@Leyart I was not able to reproduce the segfaults (which I suspect would lead to the timeout your observed).

However, we have a new version out, with significant performance improvements. In your setup, maybe 1 order of magnitude. 
Would you care to try it out?

https://github.com/opengrep/opengrep/releases/tag/v1.1.5

**Comment by Leyart** [comment]
@dimitris-m I was able to test the new version on my local machine and I can confirm that we got almost a 3x speed improvement boost at least, going from 44 mins to 15 mins on my M3.
Thanks a lot for the effort!
Would you like to keep the issue open?

**Comment by Leyart** [comment]
Thanks a lot for the effort and for remembering this Issue. I will install the new version on our agents next week and I will let you know about the outcome
